kind = "web"
previewPath = "/"
title = "Tortas y tacos de la mamá"
version = "1.0.0"
id = "artifacts/tortas-y-tacos"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19406

[services.development]
run = "pnpm --filter @workspace/tortas-y-tacos run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/tortas-y-tacos", "run", "build" ]
publicDir = "artifacts/tortas-y-tacos/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19406"
BASE_PATH = "/"
